//
//  StoryPrompts.swift
//  FlowTale
//
//  Created by iakalann on 27/11/2024.
//

import Foundation

struct StoryPrompts {
    static let all = [
        "medieval town",
        "cyberpunk city",
        "distant alien planet",
        "post-apocalyptic wasteland",
        "bustling space station",
        "underwater kingdom",
        "haunted forest",
        "magical academy",
        "steampunk airship",
        "sprawling desert bazaar",
        "small seaside village",
        "futuristic mega-city",
        "snowy mountain monastery",
        "forgotten underground temple",
        "ship stranded in the arctic",
        "ancient battlefield",
        "mysterious island",
        "cursed castle",
        "high-tech research lab",
        "crime-ridden urban neighborhood",
        "vampire-infested mansion",
        "remote wilderness outpost",
        "bustling pirate cove",
        "desert nomad camp",
        "1920s jazz club",
        "supernatural carnival",
        "secretive cult compound",
        "prehistoric jungle",
        "Victorian-era manor",
        "hidden valley of dinosaurs",
        "rebel base in a galactic war",
        "utopian society with a dark secret",
        "city where time stands still",
        "town on the edge of a black hole",
        "cursed swamp",
        "bustling train station in the Wild West",
        "magical forest glade",
        "kingdom ruled by a tyrant queen",
        "quiet suburban neighborhood with a mystery",
        "decaying amusement park",
        "royal court on the brink of war",
        "futuristic sports arena",
        "colony on Mars",
        "parallel dimension city",
        "mystical desert oasis",
        "luxurious cruise ship hiding a conspiracy",
        "space prison",
        "town where everyone disappears at night",
        "sky-high city among the clouds",
        "haunted lighthouse",
        "robot factory",
        "war-torn village",
        "wizard’s tower",
        "medieval port city",
        "remote cabin in the woods",
        "living labyrinth",
        "ruined futuristic metropolis",
        "traveling circus of magic",
        "city trapped in perpetual winter",
        "kingdom under siege",
        "enchanted library",
        "spaceship lost in uncharted space",
        "gladiatorial arena",
        "secret underground society",
        "floating island in the sky",
        "cursed mining town",
        "dimension-hopping marketplace",
        "forest where the trees whisper secrets",
        "city built on the back of a giant creature",
        "peaceful village disrupted by a prophecy",
        "secret base inside a volcano",
        "utopia run by artificial intelligence",
        "post-human Earth",
        "futuristic underwater city",
        "moon colony",
        "castle that shifts and moves at night",
        "dream-like otherworld",
        "bustling port town with hidden pirates",
        "reality TV show in space",
        "hidden bunker during a zombie apocalypse",
        "rebel spaceship in a galactic empire",
        "forgotten world inside the Earth",
        "high-stakes casino in a sci-fi setting",
        "forbidden garden with deadly plants",
        "cursed ancient ruin",
        "city on the brink of rebellion",
        "magical marketplace where anything is for sale",
        "technologically advanced jungle city",
        "labyrinthine underground city",
        "world where humans and dragons coexist",
        "small island with a deadly secret",
        "sprawling city of thieves",
        "festival where time rewinds",
        "village at the edge of a crater",
        "school for assassins",
        "colony ship en route to a new world",
        "mysterious tower in the middle of the ocean",
        "city that only appears at night",
        "realm of living shadows",
        "sprawling floating market",
        "hidden monastery guarding a terrible truth",
        "winter-bound castle with an eternal fire",
        "bustling futuristic airport",
        "village built inside a massive tree",
        "lost city of gold",
        "battle-ravaged kingdom rebuilding its future",
        "sanctuary for outlaws",
        "futuristic detective agency",
        "wasteland ruled by ruthless gangs",
        "small town harboring ancient gods",
        "neon-lit cyberpunk slum",
        "town where no one remembers the past",
        "desert with a buried alien spacecraft",
        "sanctuary for mythical creatures",
        "forest that grows overnight",
        "city that floats above a sea of lava"
    ]

}
