// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

import Foundation


public enum LocalizedString {
  public static let advanced = LocalizedString.tr("Localizable", "advanced")
  public static let aiStatement = LocalizedString.tr("Localizable", "ai_statement")
  public static let allWords = LocalizedString.tr("Localizable", "all_words")
  public static let arabicGulf = LocalizedString.tr("Localizable", "arabicGulf")
  public static let beginner = LocalizedString.tr("Localizable", "beginner")
  public static func chapterNumber(_ p1: String) -> String {
    return LocalizedString.tr("Localizable", "chapter_number", p1)
  }
  public static let chapterReady = LocalizedString.tr("Localizable", "chapter_ready")
  public static let chapters = LocalizedString.tr("Localizable", "chapters")
  public static func chaptersPerStory(_ p1: String) -> String {
    return LocalizedString.tr("Localizable", "chapters_per_story", p1)
  }
  public static let chineseMandarin = LocalizedString.tr("Localizable", "chinese_mandarin")
  public static let chooseChapter = LocalizedString.tr("Localizable", "choose_chapter")
  public static let chooseStory = LocalizedString.tr("Localizable", "choose_story")
  public static let createStory = LocalizedString.tr("Localizable", "create_story")
  public static let customStory = LocalizedString.tr("Localizable", "custom_story")
  public static let customStoryAdded = LocalizedString.tr("Localizable", "custom_story_added")
  public static let defining = LocalizedString.tr("Localizable", "defining")
  public static let definition = LocalizedString.tr("Localizable", "definition")
  public static func definitionOf(_ p1: String) -> String {
    return LocalizedString.tr("Localizable", "definition_of", p1)
  }
  public static let definitionToggle = LocalizedString.tr("Localizable", "definition_toggle")
  public static let deletedCustomStory = LocalizedString.tr("Localizable", "deleted_custom_story")
  public static let difficulty = LocalizedString.tr("Localizable", "difficulty")
  public static let done = LocalizedString.tr("Localizable", "done")
  public static let english = LocalizedString.tr("Localizable", "english")
  public static let englishToggle = LocalizedString.tr("Localizable", "english_toggle")
  public static let expert = LocalizedString.tr("Localizable", "expert")
  public static let failedModerateText = LocalizedString.tr("Localizable", "failed_moderate_text")
  public static let failedToWriteChapter = LocalizedString.tr("Localizable", "failed_to_write_chapter")
  public static let failedToWriteStory = LocalizedString.tr("Localizable", "failed_to_write_story")
  public static let failedWriteChapter = LocalizedString.tr("Localizable", "failed_write_chapter")
  public static let fast = LocalizedString.tr("Localizable", "fast")
  public static let female = LocalizedString.tr("Localizable", "female")
  public static let french = LocalizedString.tr("Localizable", "french")
  public static let german = LocalizedString.tr("Localizable", "german")
  public static let hindi = LocalizedString.tr("Localizable", "hindi")
  public static let howDifficultStory = LocalizedString.tr("Localizable", "how_difficult_story")
  public static let howStoryStart = LocalizedString.tr("Localizable", "how_story_start")
  public static let intermediate = LocalizedString.tr("Localizable", "intermediate")
  public static let japanese = LocalizedString.tr("Localizable", "japanese")
  public static let korean = LocalizedString.tr("Localizable", "korean")
  public static let language = LocalizedString.tr("Localizable", "language")
  public static let load = LocalizedString.tr("Localizable", "load")
  public static let loading = LocalizedString.tr("Localizable", "loading")
  public static let male = LocalizedString.tr("Localizable", "male")
  public static let manageSubscription = LocalizedString.tr("Localizable", "manage_subscription")
  public static let manageSubscriptionsInstructions = LocalizedString.tr("Localizable", "manage_subscriptions_instructions")
  public static let moderatingStory = LocalizedString.tr("Localizable", "moderating_story")
  public static let music = LocalizedString.tr("Localizable", "music")
  public static let newChapter = LocalizedString.tr("Localizable", "new_chapter")
  public static let newStory = LocalizedString.tr("Localizable", "new_story")
  public static let next = LocalizedString.tr("Localizable", "next")
  public static let nextChapter = LocalizedString.tr("Localizable", "next_chapter")
  public static let normal = LocalizedString.tr("Localizable", "normal")
  public static let pause = LocalizedString.tr("Localizable", "pause")
  public static let play = LocalizedString.tr("Localizable", "play")
  public static let portugueseBrazil = LocalizedString.tr("Localizable", "portuguese_brazil")
  public static let portugueseEuropean = LocalizedString.tr("Localizable", "portuguese_european")
  public static let previous = LocalizedString.tr("Localizable", "previous")
  public static func pricePerMonth(_ p1: String) -> String {
    return LocalizedString.tr("Localizable", "price_per_month", p1)
  }
  public static let privacyPolicy = LocalizedString.tr("Localizable", "privacy_policy")
  public static let random = LocalizedString.tr("Localizable", "random")
  public static let restoreSubscription = LocalizedString.tr("Localizable", "restore_subscription")
  public static let retry = LocalizedString.tr("Localizable", "retry")
  public static let reveal = LocalizedString.tr("Localizable", "reveal")
  public static let russian = LocalizedString.tr("Localizable", "russian")
  public static let saved = LocalizedString.tr("Localizable", "saved")
  public static let sentence = LocalizedString.tr("Localizable", "sentence")
  public static let settings = LocalizedString.tr("Localizable", "settings")
  public static let slow = LocalizedString.tr("Localizable", "slow")
  public static let spanish = LocalizedString.tr("Localizable", "spanish")
  public static let speed = LocalizedString.tr("Localizable", "speed")
  public static let stories = LocalizedString.tr("Localizable", "stories")
  public static let story = LocalizedString.tr("Localizable", "story")
  public static let storyDidNotMeetPolicies = LocalizedString.tr("Localizable", "story_did_not_meet_policies")
  public static let storySettings = LocalizedString.tr("Localizable", "story_settings")
  public static let studied = LocalizedString.tr("Localizable", "studied")
  public static let subscribe = LocalizedString.tr("Localizable", "subscribe")
  public static let subscriptionComplete = LocalizedString.tr("Localizable", "subscription_complete")
  public static let tapAWordToDefineIt = LocalizedString.tr("Localizable", "tap_a_word_to_define_it")
  public static let termsOfUse = LocalizedString.tr("Localizable", "terms_of_use")
  public static let toggle = LocalizedString.tr("Localizable", "toggle")
  public static let translation = LocalizedString.tr("Localizable", "translation")
  public static let unlimitedChapters = LocalizedString.tr("Localizable", "unlimited_chapters")
  public static let voice = LocalizedString.tr("Localizable", "voice")
  public static let voiceAarav = LocalizedString.tr("Localizable", "voice_aarav")
  public static let voiceAlvaro = LocalizedString.tr("Localizable", "voice_alvaro")
  public static let voiceAmala = LocalizedString.tr("Localizable", "voice_amala")
  public static let voiceAnanya = LocalizedString.tr("Localizable", "voice_ananya")
  public static let voiceAva = LocalizedString.tr("Localizable", "voice_ava")
  public static let voiceConrad = LocalizedString.tr("Localizable", "voice_conrad")
  public static let voiceDariya = LocalizedString.tr("Localizable", "voice_dariya")
  public static let voiceDenise = LocalizedString.tr("Localizable", "voice_denise")
  public static let voiceDmitry = LocalizedString.tr("Localizable", "voice_dmitry")
  public static let voiceDonato = LocalizedString.tr("Localizable", "voice_donato")
  public static let voiceDuarte = LocalizedString.tr("Localizable", "voice_duarte")
  public static let voiceElvira = LocalizedString.tr("Localizable", "voice_elvira")
  public static let voiceFatima = LocalizedString.tr("Localizable", "voice_fatima")
  public static let voiceHamdan = LocalizedString.tr("Localizable", "voice_hamdan")
  public static let voiceHenri = LocalizedString.tr("Localizable", "voice_henri")
  public static let voiceHyunSu = LocalizedString.tr("Localizable", "voice_hyun_su")
  public static let voiceKeita = LocalizedString.tr("Localizable", "voice_keita")
  public static let voiceMayu = LocalizedString.tr("Localizable", "voice_mayu")
  public static let voiceRaquel = LocalizedString.tr("Localizable", "voice_raquel")
  public static let voiceSunHi = LocalizedString.tr("Localizable", "voice_sun_hi")
  public static let voiceThalita = LocalizedString.tr("Localizable", "voice_thalita")
  public static let voiceXiaoxiao = LocalizedString.tr("Localizable", "voice_xiaoxiao")
  public static let voiceYunjian = LocalizedString.tr("Localizable", "voice_yunjian")
  public static let welcomeBack = LocalizedString.tr("Localizable", "welcome_back")
  public static let whichLanguageLearn = LocalizedString.tr("Localizable", "which_language_learn")
  public static let word = LocalizedString.tr("Localizable", "word")
  public static func wordsSaved(_ p1: String) -> String {
    return LocalizedString.tr("Localizable", "words_saved", p1)
  }
  public static func wordsStudied(_ p1: String) -> String {
    return LocalizedString.tr("Localizable", "words_studied", p1)
  }
  public static let writingChapter = LocalizedString.tr("Localizable", "writing_chapter")
  public static let writingNewChapter = LocalizedString.tr("Localizable", "writing_new_chapter")
}

extension LocalizedString {
  private static func tr(_ table: String, _ key: String, _ args: CVarArg...) -> String {
    let format = NSLocalizedString(key, tableName: table, comment: "")
    return String(format: format, locale: Locale.current, arguments: args)
  }
}
